"""PR Engine — auto-create documentation PRs when .tech.md is generated or updated."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from github import Github
    from chronicler_core.drafter.models import TechDoc


@dataclass
class PREngineConfig:
    """Configuration for PR Engine behavior."""

    branch_prefix: str = "chronicler/"
    commit_message_template: str = "docs: update {component_id} technical ledger"
    pr_title_template: str = "docs: update {component_id} .tech.md"
    pr_body_template: str = (
        "## Chronicler Auto-Generated Documentation\n\n"
        "Updated `.tech.md` for **{component_id}**.\n\n"
        "- Component: {component_id}\n"
        "- Layer: {layer}\n"
        "- Generated by: Chronicler v{version}\n"
    )
    auto_merge: bool = False
    draft: bool = True
    base_branch: str = "main"


class PREngine:
    """Auto-create documentation PRs when .tech.md is generated or updated."""

    def __init__(self, github_client: Github, config: PREngineConfig | None = None):
        self._gh = github_client
        self._config = config or PREngineConfig()

    def create_doc_pr(
        self,
        repo_name: str,
        tech_doc: TechDoc,
        branch_prefix: str | None = None,
    ) -> str:
        """Create branch, commit .tech.md, open PR. Returns PR URL."""
        prefix = branch_prefix or self._config.branch_prefix
        repo = self._gh.get_repo(repo_name)

        # Get base branch SHA
        base = repo.get_branch(self._config.base_branch)
        base_sha = base.commit.sha

        # Create branch
        branch_name = f"{prefix}{tech_doc.component_id}"
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

        # Create or update the file
        file_path = f".chronicler/{tech_doc.component_id}.tech.md"
        commit_msg = self._config.commit_message_template.format(
            component_id=tech_doc.component_id,
        )

        try:
            contents = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                file_path, commit_msg, tech_doc.raw_content, contents.sha, branch=branch_name,
            )
        except Exception:
            repo.create_file(file_path, commit_msg, tech_doc.raw_content, branch=branch_name)

        # Open PR
        pr_title = self._config.pr_title_template.format(
            component_id=tech_doc.component_id,
        )
        pr_body = self._config.pr_body_template.format(
            component_id=tech_doc.component_id,
            layer=tech_doc.frontmatter.get("layer", "unknown"),
            version=tech_doc.frontmatter.get("version", "0.1.0"),
        )
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=self._config.base_branch,
            draft=self._config.draft,
        )
        return pr.html_url

    def update_doc_pr(self, repo_name: str, pr_number: int, tech_doc: TechDoc) -> None:
        """Push updated .tech.md to an existing PR branch."""
        repo = self._gh.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        branch_name = pr.head.ref

        file_path = f".chronicler/{tech_doc.component_id}.tech.md"
        commit_msg = self._config.commit_message_template.format(
            component_id=tech_doc.component_id,
        )

        contents = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            file_path, commit_msg, tech_doc.raw_content, contents.sha, branch=branch_name,
        )

    def batch_prs(
        self,
        repo_name: str,
        docs: list[TechDoc],
        strategy: str = "one-per-repo",
    ) -> list[str]:
        """Create PRs for multiple docs.

        Strategies:
        - "one-per-repo": single PR with all docs
        - "one-per-doc": separate PR per doc
        """
        if strategy == "one-per-doc":
            return [self.create_doc_pr(repo_name, doc) for doc in docs]

        # one-per-repo: single branch, multiple commits, one PR
        repo = self._gh.get_repo(repo_name)
        base = repo.get_branch(self._config.base_branch)
        branch_name = f"{self._config.branch_prefix}batch-update"
        repo.create_git_ref(f"refs/heads/{branch_name}", base.commit.sha)

        for doc in docs:
            file_path = f".chronicler/{doc.component_id}.tech.md"
            commit_msg = self._config.commit_message_template.format(
                component_id=doc.component_id,
            )
            try:
                contents = repo.get_contents(file_path, ref=branch_name)
                repo.update_file(
                    file_path, commit_msg, doc.raw_content, contents.sha, branch=branch_name,
                )
            except Exception:
                repo.create_file(file_path, commit_msg, doc.raw_content, branch=branch_name)

        pr = repo.create_pull(
            title="docs: batch update .tech.md files",
            body=f"Updated {len(docs)} technical ledger(s).",
            head=branch_name,
            base=self._config.base_branch,
            draft=self._config.draft,
        )
        return [pr.html_url]
